language: node_js
node_js: 7
matrix:
  include:
    - os: linux
      dist: trusty
    - os: osx
      osx_image: xcode8.3
env:
  global:
  - GITHUB_REPO: bitshares/bitshares-ui
  - ORGANIZATION_REPO: bitshares/bitshares.github.io
  - WALLET_REPO: bitshares/wallet.bitshares.org
  - CXX=g++-4.8
  - secure: "KhSBX62FS4IQiaOKuPEKhTsFpzcClTo2kcGlPdHvqScjLX7vzvrGkygT97+3pxyJotKNQdxid5ewOXnRMi6lIpr8NOGx+4QWL6Itd5BS6xiWsKv/3PQcdGhRiYjMd2tDQaa6cg0k3uh8UJAoX5/v7cSC+VxrWnD3UjD3N/gtb/sYKDvFBTI3//OfRJjyGofA1RiwpT1KNrWMtqIJ98laTeu6xFydeq8BYA30jzQk41nZE10ZdIJQ72s8rzauDvdTbzlcBCdhnDiCtjjKyvLSGgGtL9FkNQLXPKtlk/ywquqi70P1u5SLwh6Ssq+aGsLjIDPBl1UZkC+GhYXijcWkNtlo5X19pn0ZksHSzQSmnrgBMB2hVJX98761eoLMFUXopFkB3Ye47WETnn0RjP5ZKwDD61338y+qpYcWW8h69xeWzvqT5a8+eOEU1hc7k9A8AjnFfb+sbs8kLEVO7bbDpHnXli+edzbkLw/3+evkevTUphBHtdBPAVUVJ9ZKputkrt8z1s5V+V4O2rB9BCky6NpIMGi+RUS2sDoDd2Ys4X9XyN/WCOoh+AwY8iLlmNUSk4SbxZSm5ZvRvbv5cZ9157MIbaoTZTGzDfsedsQMJ4xE6U2z1/61EdZWg9Rg9nFdtzIxORWT17MLlfvhX5qXIBxhTeNF3JzLWpxkYCUg1/A="
cache:
  directories:
    - "node_modules"
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
    - icnsutils
    - graphicsmagick
    - xz-utils
before_install: "./install.sh"
script: "./build.sh"
after_success: "./deploy.sh"
deploy:
  provider: releases
  tag_name: $TRAVIS_TAG
  name: $TRAVIS_TAG
  body: Automated release from Travis CI with added files from AppVeyor build
  api_key:
    secure: K+62i3Rky9rXJyO6UMTLyY+GHfQtRMpEX9bLQFyZERSdmPK5l0Xq3ivBfESczoGsIxoPuVvWLOx/ZAh+I+67izS28i5LowQKLFQQ1h1b82ilexlprkj+Gf5QE3CWk04rR4OiIv4eXJLShqnGOQ7SuyI/UHW7iwTqAOt22YWWWPazlM75JwXQBYdHZ5vY2axXW493WGnRcLqzmRBwo2Ggkieqt8QiYYtvdk4yA81qbtIK6TxLzz6pc9fW/q+r+HoB0s81djlHmOByughEgc/mW+7xB3mM2uB8katNVbGa2qgZ/NS031b04ZSe8V8JHzC6UIBU8IKuFrxm3cpFN7onYDDfKs+6x+u5LCavw3VanHCgTd4dA4Jisew2Q19YhqymYYHmhMuwLh8y8XW8V7BrNNi9qjknKodaB8SFN1PZYe29LnG07hmZWwnBkVEIXf2QwcL+yfZtJ9NmLWyktnCpj4urtz3qQOG4nkbrn9mGx+jINgfzk4bpN6jNk0wwe9yqFy7nsZxow8vHf31hICwZZl8borz6fZhW9WVDqS9bZs/Ts4Qk3U4WREdmB24eIV8W5DIliSH/5qFh0RIRDCHKisom8r2XdBATe7hJ1t+YZR0N80q2IPwgTPdVtUuHTE1YkPcu0eILgA/YUAWNu1yoSNQUYScKA2i382gOBl06CS0=
  file_glob: true
  file: build/binaries/BitShares*
  skip_cleanup: true
  draft: true
  on:
    repo: bitshares/bitshares-ui
    tags: true
