version: 1.0.{build}
environment:
  nodejs_version: "7"
install:
  # Get the latest stable version of Node.js or io.js
  - ps: Install-Product node $env:nodejs_version
  # install modules
  - npm install
build: off
test_script:
  - npm run package-win
deploy:
  provider: GitHub
  auth_token:
    secure: F/9ssjiE7swLmbl4JXtgpgv40kr3u6q+nbcNCs+Rw2S0VEMYBAXDwmKHQuAH8uDB
  artifact: build\binaries\*.exe
  draft: true
  force_update: true
  on:
    branch: 224-build-automation
